spring.application.name=FindEmp

server.port=${PORT:8080}

# Aiven MySQL Database Configuration
spring.datasource.url=jdbc:mysql://mysql-1e2aa5cc-adityarajmn203-1b1f.l.aivencloud.com:14903/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_jpPGwU5ov9ttNKdM0zC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# AI Chatbot Configuration
openrouter.api.key=sk-or-v1-1c4...a3c
gemini.api.key=${GEMINI_API_KEY}
